version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - observability

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command:
      - --config=/etc/otel-collector-config.yml
    ports:
      - "4318:4318" # OTLP HTTP endpoint
      - "9999:9999" # Prometheus metrics
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - observability
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250:14250"
    networks:
      - observability

networks:
  observability:
    driver: bridge
