global:
  scrape_interval: 15s  # How frequently Prometheus scrapes metrics

scrape_configs:
  - job_name: 'otel-collector'  # Job name for OpenTelemetry Collector
    static_configs:
      - targets: ['otel-collector:9999']  # Scraping from the Prometheus exporter on the OpenTelemetry Collector
